# spring.application.name=vuestargram
# ??? ????? ?? ?? ??

## yml? ? ??
# ?? : ???? ??
spring:
  application:
    name: vuestargram

# MariaDB 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/vuestargram
    username: root
    password: php504
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
  sql:
    init:
      data-locations: classpath*:db/data.sql
      #classpath -> resource 를 가리킴
      mode: never # 실행이 되지 않음
      # always 서버가 내려갔다가 올라올때 더미데이터가 항상 실행
      platform: all #내가 사용할 db의 dbms 설정


#config 설정
config:
  jwt:
    issuer: meerkat@green.com
    type: jwt
    access-token-expiry: 10000000
    refresh-token-expiry: 1296000000
    refresh-token-cookie-name: refresh-token
    refresh-token-cookie-expiry: 1296000
    secret: 34h6baw46bw4tvgw4tgabwz34htbw4szybhe34ybh34tgv23a4tgv3w
    header-key: Authorization
    scheme: Bearer
    reiss-uri: /api/reissue-token


# Slf4j 설정
logging:
  file:
    name: classpath:logs/app.log
  level:
    root: info